import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile,mkdtemp,writeFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {execFileSync} from 'node:child_process';
import {canonical} from '../app/model.mjs';
import {validateFragment,fragmentHash,census,delta,FOUNDING_HASH,seal,validateAdmission,reviewIdentity,snapshot,verifySnapshot,matchingDoors,validateLens,validatePrevious,validateCensus,INTENTS} from '../app/field-lifecycle.mjs';
import {readFounding,readInputs,runCensus} from '../scripts/field-census.mjs';
import {STATIC_PATHS} from '../scripts/render-field.mjs';
const root=new URL('../',import.meta.url),read=async p=>JSON.parse(await readFile(new URL(p,root),'utf8'));
const old=await readFounding(),fragments=await readInputs(new URL('census/static-web-002/inputs.json',root).pathname),c=await census(fragments,old),d=await delta(old,c),proposal=await read('census/static-web-002/public-review-proposal.json');
// Explicitly synthetic review evidence exercises the verifier. Never published.
async function admission(p=proposal){const a={schema:'webz/public-field-admission/v0',...structuredClone(p)};delete a.reviewHash;a.authority={kind:'HUMAN_PUBLIC_FIELD_REVIEW',reference:'SYNTHETIC UNIT FIXTURE; no actual human or source authority claimed.',reviewHash:await reviewIdentity(a),scope:'PUBLIC_REPRESENTATION_ONLY'};return seal(a,'admissionHash');}
const a=await admission(),s=await snapshot(old,c,a);
const clone=structuredClone;
async function badAdmission(edit,pattern){const p=clone(proposal);edit(p);await assert.rejects(()=>admission(p).then(a=>validateAdmission(a,c,old)),pattern);}
test('all founding manifest bytes reconstruct the exact historical field identity',async()=>{assert.equal(old.snapshotHash,FOUNDING_HASH);assert.equal(old.field.worlds.length,11);await validatePrevious(old);const bad=clone(old);bad.field.worlds[0].label='Retrospective rename';await assert.rejects(()=>validatePrevious(bad),/FOUNDING_HISTORY_CHANGED/);});
test('34 explicitly supplied content-addressed observations retain 17 subjects and histories',()=>{assert.equal(fragments.length,34);assert.equal(new Set(fragments.map(f=>f.subjectId)).size,17);assert.ok(fragments.every(f=>f.verification.sourceLevel==='CONTENT_ADDRESSED'));assert.equal(fragments.find(f=>f.history.pr===15&&f.source.repository.endsWith('/webZ')).history.state,'MERGED');assert.equal(fragments.find(f=>f.history.pr===12&&f.source.repository.endsWith('/webZ')).history.baseBranch,'experiment/wandering-lens-001-question-engine');assert.equal(fragments.find(f=>f.history.pr===20&&f.source.repository.endsWith('/webZ')).history.baseBranch,'main');assert.equal(fragments.find(f=>f.source.repository.endsWith('/GHoT')&&f.history.pr===113).subjectId,'riff-raft');});
test('census identity ignores argument order and retains every source-specific observation',async()=>{assert.equal((await census([...fragments].reverse(),old)).censusHash,c.censusHash);assert.equal(c.authority,'NONE');assert.equal(c.observations.length,34);assert.ok(!Object.hasOwn(c,'admission'));});
test('the exact founding delta is 15 new candidate subjects, 1 source set update, 1 unchanged, 9 not reobserved',()=>{const kinds=d.changes.flatMap(x=>x.classifications);for(const [kind,count] of [['NEW_CANDIDATE',15],['SOURCE_UPDATED',1],['UNCHANGED',1],['NOT_REOBSERVED',9]])assert.equal(kinds.filter(k=>k===kind).length,count);assert.equal(d.changes.length,26);});
test('missing input remains not observed, never withdrawal or deletion',async()=>{const one=await census([fragments.find(f=>f.subjectId==='radio-world')],old);const diff=await delta(old,one);assert.equal(diff.changes.filter(x=>x.classifications.includes('NOT_REOBSERVED')).length,10);assert.ok(diff.changes.every(x=>!x.classifications.includes('WITHDRAWN')));assert.equal(old.field.worlds.length,11);});
test('duplicate fragments and unknown relation targets refuse',async()=>{await assert.rejects(()=>census([fragments[0],fragments[0]],old),/DUPLICATE_FRAGMENT/);const f=clone(fragments[0]);f.relations=[{from:f.subjectId,to:'unknown-neighbor',kind:'references',description:'Observation only.'}];await assert.rejects(()=>census([f],old),/UNKNOWN_RELATION_TARGET/);});
for(const [name,edit,pattern] of [
 ['missing owner',f=>f.ownerClaim='',/REPOSITORY_REQUIRED/],['bad commit',f=>f.source.exactCommit='main',/SOURCE_PIN_REQUIRED/],['duplicate door',f=>f.candidateDoors.push(clone(f.candidateDoors[0])),/DUPLICATE_DOOR_ID/],['HOLD without explanation',f=>{f.candidateDoors[0]={...f.candidateDoors[0],kind:'CAPABILITY',effectClass:'REMOTE_EFFECT',availability:'HOLD',target:null,reason:''};},/BOUNDED_TEXT_REQUIRED/],['remote effect open',f=>{f.candidateDoors[0].effectClass='REMOTE_EFFECT';},/REMOTE_EFFECT_CLOSED/],['CANNON ownership relation',f=>{f.relations=[{from:f.subjectId,to:'radio-world',kind:'owns',description:'Discovery owns nothing.'}];},/RELATION_IS_NOT_AUTHORITY/],['unrecognized proof level',f=>f.verification.sourceLevel='CI_GREEN',/INVALID_PROOF_LEVEL/],['PR created grants admission',f=>f.publicAdmission=true,/INVALID_FIELDS/],['MCP implies public ChatGPT connection',f=>f.publicChatGPTConnector=true,/INVALID_FIELDS/],['Suno metadata implies account integration',f=>f.accountIntegration=true,/INVALID_FIELDS/],['newer implies greater authority',f=>f.authorityRank=99,/INVALID_FIELDS/]
])test('fragment refuses '+name,()=>{const f=clone(fragments[0]);edit(f);assert.throws(()=>validateFragment(f),pattern);});
test('exact source bytes must match the claimed content digest',async()=>{const dir=await mkdtemp(join(tmpdir(),'webz-explicit-input-'));try{await writeFile(join(dir,'f.json'),JSON.stringify(fragments[0]));await writeFile(join(dir,'source.md'),'tampered');await writeFile(join(dir,'inputs.json'),JSON.stringify({schema:'webz/explicit-census-inputs/v0',inputs:[{input:'f.json',sourceFile:'source.md',prUrl:'https://example.invalid/',patchHash:'sha256:'+'0'.repeat(64)}]}));await assert.rejects(()=>readInputs(join(dir,'inputs.json')),/SOURCE_CONTENT_MISMATCH/);}finally{await rm(dir,{recursive:true,force:true});}});
test('the census CLI has no discovery default',()=>{assert.throws(()=>execFileSync(process.execPath,['scripts/field-census.mjs'],{cwd:root,stdio:'pipe'}),/Command failed/);});
test('fragment and census hash tampering refuse even if outer census is resealed',async()=>{const bad=clone(c);bad.observations[0].fragment.humanSummary='Altered';const {censusHash,...body}=bad;await assert.rejects(async()=>validateCensus(await seal(body,'censusHash'),old),/FRAGMENT_IDENTITY_MISMATCH/);});
test('observation does not issue admission, and machine authority refuses',async()=>{const bad=clone(a);bad.authority.kind='CENSUS_TOOL';const {admissionHash,...body}=bad;await assert.rejects(async()=>validateAdmission(await seal(body,'admissionHash'),c,old),/HUMAN_ADMISSION_REQUIRED/);await assert.rejects(()=>snapshot(old,c,c));});
test('public wording cannot change after human review, even with a recomputed admission hash',async()=>{const bad=clone(a);bad.field.worlds[0].label='Different approved text';const {admissionHash,...body}=bad;await assert.rejects(async()=>validateAdmission(await seal(body,'admissionHash'),c,old),/HUMAN_REVIEW_CONTENT_MISMATCH/);});
test('a candidate not explicitly selected cannot become a public card',async()=>{await badAdmission(p=>{p.selectedFragmentHashes=p.selectedFragmentHashes.filter(h=>!c.observations.some(o=>o.fragmentHash===h&&o.fragment.subjectId==='suno-atlas'));},/UNBOUND_PUBLIC_REPRESENTATION/);});
test('CI green and PR existence cannot make LIVE',async()=>{await badAdmission(p=>p.field.worlds.at(-1).state='LIVE',/NO_REVIEWED_PUBLIC_AUTHORITY/);});
test('missing fragment cannot silently remove a prior entry',async()=>{await badAdmission(p=>p.field.worlds.shift(),/MISSING_INPUT_IS_NOT_WITHDRAWAL/);});
test('lab cannot silently become sovereign or installed world',async()=>{await badAdmission(p=>{const w=p.field.worlds.find(w=>w.id==='wandering-lens');w.state='LOCAL_ONLY';w.publicSurface={...w.publicSurface,mode:'LOCAL_ROUTE',target:'worlds/orchard/'};},/NEW_CANDIDATE_SOURCE_INSPECTION_ONLY/);});
test('Founder namespace cannot silently become hosted world',async()=>{const p=clone(proposal),f=fragments.find(f=>f.subjectId==='founder-namespace'),h=await fragmentHash(f),w=clone(p.field.worlds.at(-2));w.id='founder-namespace';w.source={repository:f.source.repository,ref:`refs/pull/${f.history.pr}/head`,exactCommit:f.source.exactCommit,observedContract:f.humanSummary};w.additionalSources=[];w.state='LOCAL_ONLY';w.publicSurface.mode='LOCAL_ROUTE';w.publicSurface.target='worlds/orchard/';w.doors=[];p.field.worlds.push(w);p.selectedFragmentHashes.push(h);p.observations.sources.push({...w.source,experiment:f.humanLabel,notClaimed:f.observedClosures,reviewedFiles:[{path:f.source.pathOrContract,sha256:f.verification.contentHash}],pr:f.history.pr,url:`https://github.com/${f.source.repository}/pull/${f.history.pr}`,patchSha256:f.verification.contentHash});await assert.rejects(()=>admission(p).then(a=>validateAdmission(a,c,old)),/NEW_CANDIDATE_SOURCE_INSPECTION_ONLY/);});
for(const [name,id] of [['Suno integration','suno-atlas-crossing'],['postal delivery','porch-delivery'],['physical printer start','printer-start'],['public VM execution','vm-public-execute']])test(name+' remains HOLD',async()=>{await badAdmission(p=>{const door=p.field.worlds.flatMap(w=>w.doors).find(d=>d.doorId===id);door.availability='AVAILABLE';door.target='https://example.org/execute';},/REMOTE_EFFECT_CLOSED/);});
test('snapshot cold replay retains exact fragments, census, admission, historical and field identities',async()=>{await verifySnapshot(s,old,c,a);assert.equal(s.field.worlds.length,13);assert.equal(s.fragments.length,8);assert.equal(s.parentSnapshotHash,FOUNDING_HASH);assert.ok(s.provenance.every(p=>p.censusHash===c.censusHash&&p.admissionHash===a.admissionHash));const tampered=clone(s);tampered.provenance[0].censusHash=FOUNDING_HASH;await assert.rejects(()=>verifySnapshot(tampered,old,c,a),/SNAPSHOT_REPLAY_MISMATCH/);});
test('a subsequent census classifies changed capability, door, HOLD, source and relation separately',async()=>{const f=clone(s.fragments.find(f=>f.subjectId==='wandering-lens'));f.observedCapabilities.push('Explicit new observation');f.observedClosures.push('Changed HOLD reason');f.candidateDoors[0].reason+=' Source update only.';f.source.exactCommit='a'.repeat(40);f.candidateDoors[0].target=`https://github.com/${f.source.repository}/tree/${f.source.exactCommit}`;f.relations=[{from:f.subjectId,to:'suno-atlas',kind:'neighbor-of',description:'Observation only.'}];const next=await census([f],s),diff=await delta(s,next);assert.deepEqual(diff.changes.find(x=>x.subjectId==='wandering-lens').classifications,['SOURCE_UPDATED','CAPABILITY_CHANGED','DOOR_CHANGED','HOLD_CHANGED','RELATION_CHANGED']);});
test('CANNON compatibility is not an execution path',()=>{const paths=clone(s.paths);paths[0].authority='EXECUTE';assert.throws(()=>validateLens(s.field,s.doorTags,paths),/PATH_IS_NOT_EXECUTION/);const f=clone(fragments.find(f=>f.externalObservation));f.externalObservation.relationClaim.compatibilityState='EXECUTION_ADMITTED';assert.throws(()=>validateFragment(f),/COMPATIBILITY_IS_NOT_EXECUTION/);});
test('paths refuse unadmitted relations and never invent cross-owner compatibility',()=>{const paths=clone(s.paths);paths[2].relationKeys=['radio-world|owns|radio-house'];assert.throws(()=>validateLens(s.field,s.doorTags,paths),/UNADMITTED_PATH_RELATION/);});
test('wayfinding matches declared intents in original field order, with no ranking and HOLD retained',()=>{for(const i of INTENTS){const result=matchingDoors(s,i);assert.ok(result.length);assert.ok(result.every(x=>!Object.hasOwn(x,'score')&&!Object.hasOwn(x,'recommendation')));const order=result.map(x=>s.field.worlds.indexOf(x.world));assert.deepEqual(order,[...order].sort((a,b)=>a-b));}assert.ok(matchingDoors(s,'PRINT').flatMap(m=>m.doors).some(d=>d.doorId==='printer-start'&&d.availability==='HOLD'));assert.ok(matchingDoors(s,'SEND').flatMap(m=>m.doors).some(d=>d.doorId==='porch-delivery'&&d.availability==='HOLD'));});
test('local search only searches admitted text, including owners and HOLD explanations',()=>{assert.equal(matchingDoors(s,'','Suno').at(0).world.id,'suno-atlas');assert.equal(matchingDoors(s,'','Conversation Collider').length,0);assert.ok(matchingDoors(s,'','HOLD').length);assert.throws(()=>matchingDoors(s,'IMPORTANCE'),/INVALID_INTENT/);});
test('candidate inputs and source documents never belong to public fixed cache',()=>{assert.ok(STATIC_PATHS.every(p=>!p.startsWith('census/')&&!p.includes('public-review-proposal')&&!p.includes('inputs.json')));});

test('an explicit withdrawal is a review candidate rather than automatic deletion',async()=>{const f=clone(fragments.find(f=>f.subjectId==='radio-world'));f.kind='WITHDRAWAL';f.observedCapabilities=[];f.observedClosures=['Explicit synthetic withdrawal source; human public review still required.'];const c2=await census([f],old),d2=await delta(old,c2);assert.deepEqual(d2.changes.find(x=>x.subjectId==='radio-world').classifications,['WITHDRAWAL_CANDIDATE']);assert.ok(old.field.worlds.some(w=>w.id==='radio-world'));});
