import {root,dialTo,enter,rise,address,parse,scope,DETAILS,LIMIT,parseKept,keep,putBack} from './navigator.mjs';
const $=id=>document.getElementById(id),KEY='abundent.garden.kept.v1';
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
let field,state=root(),focus=null,kept=[],view='garden',page=0,invalid=false;
const symbols=['tree','letter','press','cross','radio','book','cross','gear','radio','camera','tree'];
function art(i){const paths={
tree:'<path d="M65 87V42M65 67L45 53M65 59L85 43"/><path d="M30 56Q10 39 35 29Q36 10 57 20Q70 6 85 22Q108 17 112 41Q128 57 101 64Q88 77 66 65Q45 72 30 56Z" fill="#829567"/><path d="M39 89Q65 77 91 89L88 98H42Z" fill="#ae995e"/>',
letter:'<path d="M20 30H110V87H20Z" fill="#b9b391"/><path d="M20 30L65 63L110 30M20 87L48 58M110 87L82 58"/><circle cx="65" cy="63" r="9" fill="#95814e"/><path d="M66 63Q70 43 84 38M71 49Q84 50 90 42M69 53Q60 42 61 38" stroke="#879866"/>',
press:'<path d="M25 90H109M35 90V26H99V90M25 26H109M66 14V62M49 62H83V76H49Z" fill="#8b8a60"/><path d="M42 83H89" stroke="#d4c291"/><circle cx="66" cy="19" r="12" fill="#ac9a5e"/><path d="M15 98Q20 64 35 55M24 77L15 65M27 69L36 60" stroke="#9baf74"/>',
cross:'<circle cx="45" cy="53" r="26" fill="#596f58"/><circle cx="85" cy="53" r="26" fill="#8b9363"/><path d="M38 53H93M80 43L94 53L80 63" stroke="#dfcc91"/><path d="M26 90H104M35 79V90M95 79V90" stroke="#ae995e"/>',
radio:'<rect x="18" y="36" width="94" height="52" rx="7" fill="#9c925e"/><circle cx="44" cy="63" r="17" fill="#425943"/><path d="M34 57H54M34 63H54M34 69H54M68 48H101M68 54H93M29 35L41 13L37 11M71 90V97M32 90V97" stroke="#d6c493"/><circle cx="86" cy="72" r="8" fill="#4c624c"/>',
book:'<path d="M18 30Q42 22 65 35Q88 22 112 30V86Q88 78 65 91Q42 78 18 86Z" fill="#bdb28b"/><path d="M65 35V91M28 42Q43 37 55 44M28 53Q43 48 55 55M77 44Q92 37 103 42M77 55Q92 48 103 53" stroke="#526247"/><path d="M87 76Q82 54 94 43M89 61L103 55M88 65L80 55" stroke="#7f9567"/>',
gear:'<path d="M50 26L55 13H75L80 26L95 23L109 37L102 50L116 55V75L102 80L107 95L94 107L80 100L75 115H55L50 101L35 105L23 92L30 79L16 74V55L29 50L25 35L38 23Z" fill="#9b965e" transform="translate(8 0) scale(.85)"/><circle cx="64" cy="56" r="23" fill="#3b5943"/><circle cx="64" cy="56" r="10" fill="#b5ab70"/><path d="M29 99Q22 72 17 67M26 90L13 81M23 79L29 69" stroke="#94ae6c"/>',
camera:'<path d="M24 39H106V87H24Z" fill="#8b9167"/><path d="M42 39V29H78V39M18 90H112M85 39V16M79 16H92" stroke="#cabb82"/><circle cx="65" cy="62" r="22" fill="#3c5144"/><circle cx="65" cy="62" r="13" fill="#7d9c8c"/><path d="M96 9L100 2M105 13L117 9M106 20L116 25" stroke="#d5bd78"/>'};
const box=el('div',undefined,'art');box.innerHTML='<svg viewBox="0 0 130 120" xmlns="http://www.w3.org/2000/svg" aria-hidden="true"><g stroke="#293e2b" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">'+paths[symbols[i]||'tree']+'</g><path d="M5 105Q40 95 126 106" stroke="#809365" fill="none"/></svg>';return box;}
function notice(msg){$('notice').hidden=!msg;$('notice').textContent=msg||'';}
function navigate(next){state=next;invalid=false;page=0;view='garden';const hash='#'+address(state);if(location.hash!==hash)history.pushState(null,'',hash);notice('');render();}
function restore(){try{state=location.hash?parse(decodeURIComponent(location.hash.slice(1))):root();invalid=false;notice('');}catch(e){state=root();invalid=true;notice(e.message==='STALE_CATALOG_ADDRESS'?'This place belongs to another catalog. Its address is preserved. Choose Root to begin in this garden.':'This garden address could not be read. It is preserved. Choose Root to begin again.');}page=0;render();}
function link(text,target,cls){const a=el('a',text,cls);a.href=target;a.target='_blank';a.rel='noopener noreferrer';a.setAttribute('aria-label',text+' (opens in a new tab)');return a;}
function render(){const current=scope(field,state);$('tuning').value=state.tuning-1;$('granularity').value=state.granularity-1;$('t-val').textContent=state.tuning-1;$('g-val').textContent=state.granularity-1;$('t-name').textContent=current.lane?.name||'An empty clearing';$('g-name').textContent=current.detail;for(const [id,n] of [['tuning-face',state.tuning],['detail-face',state.granularity]])$(id).style.setProperty('--angle',(-135+(n-1)*27)+'deg');
$('tuning').setAttribute('aria-valuetext',(state.tuning-1)+': '+(current.lane?.name||'Empty position'));$('granularity').setAttribute('aria-valuetext',(state.granularity-1)+': '+current.detail);$('readout').textContent=invalid?'—':current.worlds.length;$('enter').disabled=invalid||!current.worlds.length||state.path.length>=LIMIT;$('rise').disabled=invalid||!state.path.length;$('original').href='https://abundent.org/field/navigate/#'+address(state);$('original').hidden=invalid;$('copy').disabled=invalid;
$('trail').textContent=(current.trail.join(' → ')||'Root garden')+' · depth '+state.path.length;$('tray-label').textContent=view==='kept'?'KEPT ON YOUR BENCH':'ON THE DISCOVERY TRAY';$('kept-count').textContent=kept.length;document.querySelectorAll('[data-view]').forEach(n=>n.classList.toggle('active',n.dataset.view===view));
const worlds=invalid?[]:view==='kept'?field.worlds.filter(w=>kept.includes(w.id)):current.worlds;const total=Math.max(1,Math.ceil(worlds.length/6));page=Math.min(page,total-1);$('page').textContent=String(page+1).padStart(2,'0')+' / '+String(total).padStart(2,'0');$('prev').disabled=page===0;$('next').disabled=page>=total-1;$('tray').replaceChildren();
if(!worlds.length){const b=el('article',undefined,'blank');b.append(el('h2',view==='kept'?'A little room for something good.':'An empty clearing.'),el('p',view==='kept'?'Inspect a world, then keep it on your bench.':'Turn the field dial, Rise, or return to Root.'));$('tray').append(b);}
for(const w of worlds.slice(page*6,page*6+6)){const i=field.worlds.indexOf(w),c=el('article',undefined,'card'+(focus===w.id?' selected':''));const image=art(i);image.append(el('span','FIELD '+String(i+1).padStart(2,'0'),'serial'));if(kept.includes(w.id))image.append(el('span','❋','kept-mark'));const b=el('div',undefined,'card-body');b.append(el('div',w.category+' / '+w.ownerSystem,'eyebrow'),el('h2',w.label),el('p',w.shortDescription));if(state.granularity>=4)b.append(el('p',w.current,'detail'));if(state.granularity>=5)b.append(el('p',w.state.replaceAll('_',' ')+' · '+w.doors.filter(d=>d.availability==='AVAILABLE').length+' open doors','detail'));const btn=el('button','Inspect this world ↗');btn.setAttribute('aria-label','Inspect '+w.label);btn.onclick=()=>{focus=w.id;render();$('inspection').querySelector('h2')?.focus();};b.append(btn);c.append(image,b);$('tray').append(c);}inspector();}
function inspector(){const w=field.worlds.find(w=>w.id===focus);if(!w)return;document.querySelector('.inspector').classList.add('open');$('inspection').replaceChildren();const i=field.worlds.indexOf(w),a=el('div',undefined,'inspect-art');a.append(art(i));const title=el('h2',w.label,'inspect-title');title.tabIndex=-1;$('inspection').append(a,el('div',w.category+' / '+w.ownerSystem,'eyebrow'),title,el('p',w.shortDescription,'inspect-text'));
const keptHere=kept.includes(w.id),b=el('button',keptHere?'Put back into the garden':'Keep on my bench ❋','keep-button');b.onclick=()=>{kept=keptHere?putBack(kept,w.id):keep(kept,w.id);try{localStorage.setItem(KEY,JSON.stringify(kept));}catch{notice('Your bench is kept for this visit. Browser storage is unavailable.');}render();};$('inspection').append(b);
const s=scope(field,state);$('inspection').append(el('p',(s.worlds.some(x=>x.id===w.id)?'In view: '+(s.lane?.name||'this field'):'Selected from another field.')+'. Keeping is a browser-local bookmark.','inspect-text'));
for(const d of w.doors){if(d.availability==='AVAILABLE'&&d.target){const target=d.effectClass==='EXTERNAL_NAVIGATION'?d.target:new URL(d.target,'https://abundent.org/').href;$('inspection').append(link(d.label+' ↗',target,'door-link'));}else{const row=el('div',undefined,'held');row.append(el('strong',d.availability+' · '+d.label));if(state.granularity>=7)row.append(el('div',d.reason));if(state.granularity>=8)row.append(el('div','Next: '+d.requiredNextAuthority));$('inspection').append(row);}}
const source=el('details',undefined,'source');source.open=state.granularity>=9;source.append(el('summary','ROOTS & SOURCE / OBSERVED 09 OCT 2026'),el('p',w.current),el('p',w.source.repository),el('code',w.source.exactCommit),link('Inspect the original source ↗','https://github.com/'+w.source.repository+'/tree/'+w.source.exactCommit));if(state.granularity>=10)source.append(el('p',w.laws.join(' · ')));if(state.granularity>=11)source.append(el('p',w.authoritySummary),el('p','Next gate: '+w.nextGate));$('inspection').append(source);}
try{const r=await fetch(new URL('../field/public-field.json',import.meta.url));if(!r.ok)throw Error('catalog');field=await r.json();if(field.worlds.length!==11)throw Error('catalog');try{kept=parseKept(localStorage.getItem(KEY),field.worlds.map(w=>w.id));}catch{}for(const axis of ['tuning','granularity'])$(axis).oninput=()=>navigate(dialTo(state,axis,+$(axis).value+1));$('enter').onclick=()=>navigate(enter(state));$('rise').onclick=()=>navigate(rise(state));$('root').onclick=()=>navigate(root());$('prev').onclick=()=>{page--;render();};$('next').onclick=()=>{page++;render();};$('close').onclick=()=>{focus=null;document.querySelector('.inspector').classList.remove('open');$('inspection').replaceChildren(el('p','Inspect something on the tray.','inspect-text'));render();};document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;page=0;if(view==='garden'){navigate(root());}else render();});document.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>{focus=b.dataset.id;render();});$('copy').onclick=async()=>{try{await navigator.clipboard.writeText(location.origin+location.pathname+'#'+address(state));notice('This garden address is copied.');}catch{notice('This place: '+address(state));}};addEventListener('popstate',restore);addEventListener('hashchange',restore);restore();}catch{notice('The garden catalog could not be loaded. Visit the plain field using the link below.');$('enter').disabled=true;}
